CREATE TABLE INFO (
        SN VARCHAR(9) NOT NULL PRIMARY KEY,
        SYSINFO VARCHAR(50) NOT NULL,
        CPU_TYPE VARCHAR(15) NOT NULL,
        MEM VARCHAR(15),
        DISK VARCHAR(30) NOT NULL,
        IPADD_PUB VARCHAR(15) NOT NULL,
        IPADD_IN VARCHAR(15) NOT NULL
);
